name: sura_online_shopping_admin
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  formz: ^0.4.1
  json_annotation: ^4.6.0

  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_storage: ^10.3.7

  internet_connection_checker: ^0.0.1+4

  cupertino_icons: ^1.0.2
  
  camera: ^0.10.0+1
  image_picker: ^0.8.5+3

  
  flutter_bloc: 
  bloc: 

  lottie: ^1.4.1
  intl_phone_field: ^3.1.0
  google_fonts: ^3.0.1
  overlay_support: ^2.0.1
  pinput: ^2.2.12
  animated_splash_screen: ^1.3.0
  progress_indicators: ^1.0.0
  smooth_page_indicator:
  

  path_provider: ^2.0.11
  path: ^1.8.2

  sembast: ^3.2.0+1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1  
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.7
 

flutter:
  assets:
    - assets/splash/
    - assets/image/
    - assets/fonts/
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
